spring:
  datasource:
    url: jdbc:h2:mem:vault
    username: sa
    password:
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true